/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@tenet/eval-(.*)$': '<rootDir>/eval/$1/src',
    '^@tenet/models-(.*)$': '<rootDir>/models/$1/src',
    '^@tenet/surface-(.*)$': '<rootDir>/surfaces/$1/src',
    '^@tenet/connectors-(.*)$': '<rootDir>/connectors/$1/src',
    '^@tenet/stores-vector-(.*)$': '<rootDir>/stores/vector/$1/src',
    '^@tenet/stores-state-(.*)$': '<rootDir>/stores/state/$1/src',
    '^@tenet/app-(.*)$': '<rootDir>/apps/$1/src',
    '^@tenet/rerank-(.*)$': '<rootDir>/packages/rerank-$1/src',
    '^@tenet/judge-(.*)$': '<rootDir>/packages/judge-$1/src',
    '^@tenet/voice-(.*)$': '<rootDir>/packages/voice-$1/src',
    '^@tenet/voice$': '<rootDir>/packages/voice/src',
    '^@tenet/(.*)$': '<rootDir>/packages/$1/src',
  },
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: {
          target: 'ES2023',
          module: 'ESNext',
          moduleResolution: 'Bundler',
          strict: true,
          esModuleInterop: true,
          isolatedModules: true,
        },
      },
    ],
  },
  testMatch: [
    '<rootDir>/packages/*/src/**/*.test.ts',
    '<rootDir>/models/*/src/**/*.test.ts',
    '<rootDir>/surfaces/*/src/**/*.test.ts',
    '<rootDir>/connectors/*/src/**/*.test.ts',
    '<rootDir>/stores/*/*/src/**/*.test.ts',
    '<rootDir>/stores/*/src/**/*.test.ts',
    '<rootDir>/apps/*/src/**/*.test.ts',
    '<rootDir>/eval/*/src/**/*.test.ts',
  ],
  collectCoverageFrom: [
    'packages/*/src/**/*.ts',
    'models/*/src/**/*.ts',
    'surfaces/*/src/**/*.ts',
    'connectors/*/src/**/*.ts',
    'stores/*/*/src/**/*.ts',
    'apps/*/src/**/*.ts',
    '!**/src/**/*.test.ts',
    '!**/src/index.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  testTimeout: 10_000,
};
