{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tenet.fullname" . }}
  labels:
    {{- include "tenet.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tenet.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
